# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'load_feed.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_load_feed_dialog(object):
    def setupUi(self, load_feed_dialog):
        load_feed_dialog.setObjectName("load_feed_dialog")
        load_feed_dialog.resize(329, 448)
        load_feed_dialog.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(load_feed_dialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.manual_input_button = QtWidgets.QPushButton(load_feed_dialog)
        self.manual_input_button.setObjectName("manual_input_button")
        self.horizontalLayout.addWidget(self.manual_input_button)
        self.load_text_button = QtWidgets.QPushButton(load_feed_dialog)
        self.load_text_button.setObjectName("load_text_button")
        self.horizontalLayout.addWidget(self.load_text_button)
        self.clean_aged_button = QtWidgets.QPushButton(load_feed_dialog)
        self.clean_aged_button.setObjectName("clean_aged_button")
        self.horizontalLayout.addWidget(self.clean_aged_button)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.line = QtWidgets.QFrame(load_feed_dialog)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.action_buttons = QtWidgets.QHBoxLayout()
        self.action_buttons.setSpacing(6)
        self.action_buttons.setObjectName("action_buttons")
        self.add_feed_button = QtWidgets.QPushButton(load_feed_dialog)
        self.add_feed_button.setEnabled(True)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/res/res/add.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.add_feed_button.setIcon(icon)
        self.add_feed_button.setObjectName("add_feed_button")
        self.action_buttons.addWidget(self.add_feed_button)
        self.remove_feed_button = QtWidgets.QPushButton(load_feed_dialog)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/res/res/remove.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.remove_feed_button.setIcon(icon1)
        self.remove_feed_button.setCheckable(False)
        self.remove_feed_button.setObjectName("remove_feed_button")
        self.action_buttons.addWidget(self.remove_feed_button)
        self.load_feed_button = QtWidgets.QPushButton(load_feed_dialog)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/res/res/loadfeed.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.load_feed_button.setIcon(icon2)
        self.load_feed_button.setObjectName("load_feed_button")
        self.action_buttons.addWidget(self.load_feed_button)
        self.verticalLayout_2.addLayout(self.action_buttons)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.feed_list_ui = QtWidgets.QListWidget(load_feed_dialog)
        self.feed_list_ui.setProperty("isWrapping", False)
        self.feed_list_ui.setWordWrap(False)
        self.feed_list_ui.setObjectName("feed_list_ui")
        self.verticalLayout.addWidget(self.feed_list_ui)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.progressBar = QtWidgets.QProgressBar(load_feed_dialog)
        self.progressBar.setEnabled(False)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_2.addWidget(self.progressBar)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.status_label = QtWidgets.QLabel(load_feed_dialog)
        self.status_label.setObjectName("status_label")
        self.horizontalLayout_2.addWidget(self.status_label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.abort_button = QtWidgets.QPushButton(load_feed_dialog)
        self.abort_button.setObjectName("abort_button")
        self.horizontalLayout_2.addWidget(self.abort_button)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)

        self.retranslateUi(load_feed_dialog)
        QtCore.QMetaObject.connectSlotsByName(load_feed_dialog)

    def retranslateUi(self, load_feed_dialog):
        _translate = QtCore.QCoreApplication.translate
        load_feed_dialog.setWindowTitle(_translate("load_feed_dialog", "Load from Feed"))
        self.manual_input_button.setText(_translate("load_feed_dialog", "Maual Input"))
        self.load_text_button.setText(_translate("load_feed_dialog", "Load From Text File"))
        self.clean_aged_button.setText(_translate("load_feed_dialog", "Clean Aged Data"))
        self.add_feed_button.setText(_translate("load_feed_dialog", "Add Feed"))
        self.remove_feed_button.setText(_translate("load_feed_dialog", "Remove Feed"))
        self.load_feed_button.setText(_translate("load_feed_dialog", "Load from Feed"))
        self.status_label.setText(_translate("load_feed_dialog", "   "))
        self.abort_button.setText(_translate("load_feed_dialog", "Abort"))

from . import myRes_rc
