# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'view_doc.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_view_doc_dialog(object):
    def setupUi(self, view_doc_dialog):
        view_doc_dialog.setObjectName("view_doc_dialog")
        view_doc_dialog.resize(582, 465)
        view_doc_dialog.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(view_doc_dialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.prev_button = QtWidgets.QPushButton(view_doc_dialog)
        self.prev_button.setAutoDefault(False)
        self.prev_button.setObjectName("prev_button")
        self.horizontalLayout.addWidget(self.prev_button)
        self.cur_page_no_edit = QtWidgets.QLineEdit(view_doc_dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cur_page_no_edit.sizePolicy().hasHeightForWidth())
        self.cur_page_no_edit.setSizePolicy(sizePolicy)
        self.cur_page_no_edit.setMinimumSize(QtCore.QSize(0, 0))
        self.cur_page_no_edit.setBaseSize(QtCore.QSize(0, 0))
        self.cur_page_no_edit.setObjectName("cur_page_no_edit")
        self.horizontalLayout.addWidget(self.cur_page_no_edit)
        self.count_label = QtWidgets.QLabel(view_doc_dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.count_label.sizePolicy().hasHeightForWidth())
        self.count_label.setSizePolicy(sizePolicy)
        self.count_label.setObjectName("count_label")
        self.horizontalLayout.addWidget(self.count_label)
        self.next_button = QtWidgets.QPushButton(view_doc_dialog)
        self.next_button.setDefault(True)
        self.next_button.setObjectName("next_button")
        self.horizontalLayout.addWidget(self.next_button)
        self.del_doc_button = QtWidgets.QPushButton(view_doc_dialog)
        self.del_doc_button.setObjectName("del_doc_button")
        self.horizontalLayout.addWidget(self.del_doc_button)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.line = QtWidgets.QFrame(view_doc_dialog)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(view_doc_dialog)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.title_label = QtWidgets.QLabel(view_doc_dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.title_label.sizePolicy().hasHeightForWidth())
        self.title_label.setSizePolicy(sizePolicy)
        self.title_label.setText("")
        self.title_label.setWordWrap(True)
        self.title_label.setObjectName("title_label")
        self.horizontalLayout_2.addWidget(self.title_label)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(view_doc_dialog)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.link_label = QtWidgets.QLabel(view_doc_dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.link_label.sizePolicy().hasHeightForWidth())
        self.link_label.setSizePolicy(sizePolicy)
        self.link_label.setWordWrap(True)
        self.link_label.setOpenExternalLinks(True)
        self.link_label.setObjectName("link_label")
        self.horizontalLayout_3.addWidget(self.link_label)
        self.feed_updated_label = QtWidgets.QLabel(view_doc_dialog)
        self.feed_updated_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.feed_updated_label.setObjectName("feed_updated_label")
        self.horizontalLayout_3.addWidget(self.feed_updated_label)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.desc_view_Layout = QtWidgets.QVBoxLayout()
        self.desc_view_Layout.setObjectName("desc_view_Layout")
        self.verticalLayout_2.addLayout(self.desc_view_Layout)
        self.progressBar = QtWidgets.QProgressBar(view_doc_dialog)
        self.progressBar.setEnabled(False)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_2.addWidget(self.progressBar)

        self.retranslateUi(view_doc_dialog)
        QtCore.QMetaObject.connectSlotsByName(view_doc_dialog)

    def retranslateUi(self, view_doc_dialog):
        _translate = QtCore.QCoreApplication.translate
        view_doc_dialog.setWindowTitle(_translate("view_doc_dialog", "View Doc"))
        self.prev_button.setText(_translate("view_doc_dialog", "Previous"))
        self.cur_page_no_edit.setText(_translate("view_doc_dialog", "123"))
        self.count_label.setText(_translate("view_doc_dialog", "TextLabel"))
        self.next_button.setText(_translate("view_doc_dialog", "Next"))
        self.del_doc_button.setText(_translate("view_doc_dialog", "Delete Doc"))
        self.label.setText(_translate("view_doc_dialog", "Title: "))
        self.label_3.setText(_translate("view_doc_dialog", "Link: "))
        self.link_label.setText(_translate("view_doc_dialog", "- - - - -"))
        self.feed_updated_label.setText(_translate("view_doc_dialog", "TextLabel"))

from . import myRes_rc
